version: 2.1
jobs:
  lint-dockerfile:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Create bin directory in the home directory
          command: mkdir -p $HOME/bin
      - run:
          name: Install hadolint
          command: |
            curl -L https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64 -o $HOME/bin/hadolint
            chmod +x $HOME/bin/hadolint
      - run:
          name: Add bin to PATH
          command: echo 'export PATH=$HOME/bin:$PATH' >> $BASH_ENV
      - run:
          name: Lint Dockerfile
          command: hadolint Dockerfile

  test-app:
    docker:
      - image: cimg/go:1.20
    steps:
      - checkout
      - restore_cache:
          key: go-mod-{{ checksum "go.sum" }}
      - run:
          name: Download Go modules
          command: go mod download
      - run:
          name: Run Unit Tests
          command: go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    machine:
      docker_layer_caching: true
      resource_class: medium
    steps:
      - checkout
      - run:
          name: Print Working Directory
          command: pwd
      - run:
          name: List Files
          command: ls -la
      - run:
          name: Fix Script Permissions
          command: chmod +x ./build_push_image_karsajobs.sh
      - run:
          name: Verify Permissions
          command: ls -la ./build_push_image_karsajobs.sh
      - run:
          name: Run Deployment Script
          command: ./build_push_image_karsajobs.sh

workflows:
  build-and-test:
    jobs:
      - lint-dockerfile
      - test-app:
          requires:
            - lint-dockerfile
      - build-app-karsajobs:
          requires:
            - test-app
