version: 2.1

jobs:
  install_dependencies:
    docker:
      - image: cimg/node:18.17 
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install

  lint-dockerfile:
  # berisi proses untuk menginstal hadolint dan menjalankannya terhadap berkas Dockerfile.
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Create bin directory in the home directory
          command: mkdir -p $HOME/bin
      - run:
          name: Install hadolint
          command: |
            curl -L https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64 -o $HOME/bin/hadolint
            chmod +x $HOME/bin/hadolint
      - run:
          name: Add bin to PATH
          command: echo 'export PATH=$HOME/bin:$PATH' >> $BASH_ENV
      - run:
          name: Lint Dockerfile
          command: hadolint Dockerfile

  build-app-karsajobs-ui:
  # berisi perintah untuk build dan push image.
    machine:
      docker_layer_caching: true
      resource_class: medium
    steps:
      - checkout
      - run:
          name: Fix Script Permissions
          command: chmod +x ./build_push_image_karsajobs.sh
      - run:
          name: Verify Permissions
          command: ls -la ./build_push_image_karsajobs.sh
      - run:
          name: Run Deployment Script
          command: ./build_push_image_karsajobs.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - install_dependencies
      - lint-dockerfile:
          requires:
            - install_dependencies
      - build-app-karsajobs-ui:
          requires:
            - lint-dockerfile