version: 2.1

jobs:
  install_dependencies:
    docker:
      - image: cimg/node:18.17   #pull image node dari docker hub
    steps:
      - checkout
      - run:
          name: Install dependencies #install node
          command: npm install

  lint-dockerfile:
  # berisi proses untuk menginstal hadolint dan menjalankannya terhadap berkas Dockerfile.
    docker:
      - image: circleci/python:3.8 #pull image python dari docker hub
    steps:
      - checkout
      - run:
          name: Create bin directory in the home directory
          command: mkdir -p $HOME/bin
      - run:
          name: Install hadolint #install halolint
          command: |
            curl -L https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64 -o $HOME/bin/hadolint
            chmod +x $HOME/bin/hadolint
      - run:
          name: Add bin to PATH
          command: echo 'export PATH=$HOME/bin:$PATH' >> $BASH_ENV
      - run:
          name: Lint Dockerfile #melakukan lint halolint pada Dockerfile
          command: hadolint Dockerfile

  build-app-karsajobs-ui:
  # berisi perintah untuk build dan push image.
    machine:
      docker_layer_caching: true
      resource_class: medium
    steps:
      - checkout
      - run:
          name: Fix Script Permissions #check integritas scrpit permission
          command: chmod +x ./build_push_image_karsajobs.sh
      - run:
          name: Verify Permissions #validasi/verify permission
          command: ls -la ./build_push_image_karsajobs.sh
      - run:
          name: Run Deployment Script #eksekusi script untuk deploy ke github packages
          command: ./build_push_image_karsajobs.sh

workflows: #eksekusi sesuai workflow/pipeline step by step
  version: 2
  build_and_test:
    jobs:
      - install_dependencies
      - lint-dockerfile:
          requires:
            - install_dependencies
      - build-app-karsajobs-ui:
          requires:
            - lint-dockerfile