version: 2.1

jobs:
  install_dependencies:
    docker:
      - image: cimg/node:18.17 # Updated to use the latest available image
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install

  lint:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout
      - run:
          name: Run linter
          command: npm run lint

  test:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout
      - run:
          name: Run tests
          command: npm run test

  build:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build the application
          command: npm run build

workflows:
  version: 2
  build_and_test:
    jobs:
      - install_dependencies
      - lint:
          requires:
            - install_dependencies
      - test:
          requires:
            - install_dependencies
      - build:
          requires:
            - test